In [2]:
import numpy as np
pos1 = np.array([0.0, 1.5e11])   # Initial position of body 1, m
pos2 = np.array([0.0, -1.5e11])  # Initial position of body 2, m
vel1 = np.array([3e4, 0.0])      # Initial velocity of body 1, m/s
vel2 = np.array([-3e4, 0.0])     # Initial velocity of body 2, m/s

positions1 = [pos1]
positions2 = [pos2]

In [3]:
pos2-pos1

array([ 0.e+00, -3.e+11])

In [5]:
np.linalg.norm(pos2-pos1)

300000000000.0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Constants
G = 6.67430e-11  # Gravitational constant, m^3 kg^-1 s^-2
M1 = 2.0e30      # Mass of the first body (e.g., a star), kg
M2 = 1.5e30      # Mass of the second body, kg
dt = 1e5         # Time step, seconds

# Initial positions and velocities (arbitrary)
pos1 = np.array([0.0, 1.5e11])   # Initial position of body 1, m
pos2 = np.array([0.0, -1.5e11])  # Initial position of body 2, m
vel1 = np.array([3e4, 0.0])      # Initial velocity of body 1, m/s
vel2 = np.array([-3e4, 0.0])     # Initial velocity of body 2, m/s

positions1 = [pos1]
positions2 = [pos2]

# Function to compute gravitational force
def gravitational_force(pos1, pos2, M1, M2):
    r_vec = pos2 - pos1
    r_mag = np.linalg.norm(r_vec)
    r_hat = r_vec / r_mag
    force_mag = G * M1 * M2 / r_mag**2
    force_vec = force_mag * r_hat
    return force_vec

# Simulate the motion for a set number of time steps
num_steps = 10000
for _ in range(num_steps):
    # Compute forces
    force_on_1 = gravitational_force(pos1, pos2, M1, M2)
    force_on_2 = -force_on_1  # Equal and opposite
    dvdt

    # Update positions
    pos1 += vel1 * dt
    pos2 += vel2 * dt

    # Store positions
    positions1.append(pos1)
    positions2.append(pos2)

# Convert positions to arrays for easy plotting
positions1 = np.array(positions1)
positions2 = np.array(positions2)
print(positions1,'\n','this 2',positions2)

In [12]:
import pandas as pd

In [19]:
pd.DataFrame(positions1,columns=['x1','y1'])

x1            y1
0      2.314288e+13 -5.272075e+12
1      3.000000e+09  1.499889e+11
2      5.999778e+09  1.499666e+11
3      8.999111e+09  1.499333e+11
4      1.199778e+10  1.498889e+11
...             ...           ...
9996   2.313371e+13 -5.269911e+12
9997   2.313600e+13 -5.270452e+12
9998   2.313829e+13 -5.270993e+12
9999   2.314059e+13 -5.271534e+12
10000  2.314288e+13 -5.272075e+12

[10001 rows x 2 columns]

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Constants
G = 6.67430e-11  # Gravitational constant, m^3 kg^-1 s^-2
M1 = 2.0e30      # Mass of the first body (e.g., a star), kg
M2 = 1.5e30      # Mass of the second body, kg
dt = 1e5         # Time step, seconds

# Initial positions and velocities (arbitrary)
pos1 = np.array([-1.0e11, 0.0])   # Initial position of body 1, m
pos2 = np.array([1.0e11, 0.0])    # Initial position of body 2, m
vel1 = np.array([0.0, 1.0e4])     # Initial velocity of body 1, m/s
vel2 = np.array([0.0, -1.5e4])    # Initial velocity of body 2, m/s

positions1 = [pos1]
positions2 = [pos2]

# Function to compute gravitational force
def gravitational_force(pos1, pos2, M1, M2):
    r_vec = pos2 - pos1
    r_mag = np.linalg.norm(r_vec)
    r_hat = r_vec / r_mag
    force_mag = G * M1 * M2 / r_mag**2
    force_vec = force_mag * r_hat
    return force_vec

# Simulate the motion for a set number of time steps
num_steps = 5000
for _ in range(num_steps):
    # Compute forces
    force_on_1 = gravitational_force(pos1, pos2, M1, M2)
    force_on_2 = -force_on_1  # Equal and opposite

    # Update velocities
    vel1 += (force_on_1 / M1) * dt
    vel2 += (force_on_2 / M2) * dt

    # Update positions
    pos1 += vel1 * dt
    pos2 += vel2 * dt

    # Store positions
    positions1.append(pos1.copy())
    positions2.append(pos2.copy())

In [22]:
positions1

[array([-9.48051805e+10, -3.39515157e+11]),
 array([-9.99749714e+10,  1.00000000e+09]),
 array([-9.99249054e+10,  1.99968694e+09]),
 array([-9.98497904e+10,  2.99874720e+09]),
 array([-9.97496118e+10,  3.99686629e+09]),
 array([-9.96243523e+10,  4.99372858e+09]),
 array([-9.94739914e+10,  5.98901698e+09]),
 array([-9.92985061e+10,  6.98241265e+09]),
 array([-9.90978703e+10,  7.97359468e+09]),
 array([-9.88720549e+10,  8.96223982e+09]),
 array([-9.86210281e+10,  9.94802211e+09]),
 array([-9.83447552e+10,  1.09306126e+10]),
 array([-9.80431987e+10,  1.19096790e+10]),
 array([-9.77163180e+10,  1.28848853e+10]),
 array([-9.73640700e+10,  1.38558917e+10]),
 array([-9.69864086e+10,  1.48223536e+10]),
 array([-9.65832849e+10,  1.57839221e+10]),
 array([-9.61546471e+10,  1.67402429e+10]),
 array([-9.57004410e+10,  1.76909564e+10]),
 array([-9.52206094e+10,  1.86356969e+10]),
 array([-9.47150923e+10,  1.95740925e+10]),
 array([-9.41838274e+10,  2.05057645e+10]),
 array([-9.36267495e+10,  2.1430

In [23]:
positions2

[array([ 9.30735740e+10, -3.80646458e+11]),
 array([ 9.99666285e+10, -1.50000000e+09]),
 array([ 9.98998738e+10, -2.99958259e+09]),
 array([ 9.97997205e+10, -4.49832960e+09]),
 array([ 9.96661491e+10, -5.99582172e+09]),
 array([ 9.94991363e+10, -7.49163811e+09]),
 array([ 9.92986553e+10, -8.98535597e+09]),
 array([ 9.90646749e+10, -1.04765502e+10]),
 array([ 9.87971604e+10, -1.19647929e+10]),
 array([ 9.84960732e+10, -1.34496531e+10]),
 array([ 9.81613708e+10, -1.49306961e+10]),
 array([ 9.77930070e+10, -1.64074835e+10]),
 array([ 9.73909316e+10, -1.78795720e+10]),
 array([ 9.69550907e+10, -1.93465138e+10]),
 array([ 9.64854267e+10, -2.08078556e+10]),
 array([ 9.59818781e+10, -2.22631381e+10]),
 array([ 9.54443798e+10, -2.37118961e+10]),
 array([ 9.48728628e+10, -2.51536572e+10]),
 array([ 9.42672547e+10, -2.65879418e+10]),
 array([ 9.36274791e+10, -2.80142625e+10]),
 array([ 9.29534564e+10, -2.94321233e+10]),
 array([ 9.22451032e+10, -3.08410193e+10]),
 array([ 9.15023327e+10, -3.2240

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Constants
G = 6.67430e-11  # Gravitational constant, m^3 kg^-1 s^-2
M1 = 2.0e30      # Mass of the first body (e.g., a star), kg
M2 = 1.5e30      # Mass of the second body, kg
dt = 1e5         # Time step, seconds

# Initial positions and velocities (arbitrary)
pos1 = np.array([-1.0e11, 0.0])   # Initial position of body 1, m
pos2 = np.array([1.0e11, 0.0])    # Initial position of body 2, m
vel1 = np.array([0.0, 1.0e4])     # Initial velocity of body 1, m/s
vel2 = np.array([0.0, -1.5e4])    # Initial velocity of body 2, m/s

positions1 = [pos1]
positions2 = [pos2]

# Function to compute gravitational force
def gravitational_force(pos1, pos2, M1, M2):
    r_vec = pos2 - pos1
    r_mag = np.linalg.norm(r_vec)
    r_hat = r_vec / r_mag
    force_mag = G * M1 * M2 / r_mag**2
    force_vec = force_mag * r_hat
    return force_vec

# Simulate the motion for a set number of time steps
num_steps = 10000
for _ in range(num_steps):
    # Compute forces
    force_on_1 = gravitational_force(pos1, pos2, M1, M2)
    force_on_2 = -force_on_1  # Equal and opposite

    # Update velocities
    vel1 += (force_on_1 / M1) * dt
    vel2 += (force_on_2 / M2) * dt

    # Update positions
    pos1 += vel1 * dt
    pos2 += vel2 * dt

    # Store positions
    positions1.append(pos1.copy())
    positions2.append(pos2.copy())

# Convert positions to arrays for easy plotting
positions1 = np.array(positions1[1:])
positions2 = np.array(positions2[1:])

# Create the animation
# fig, ax = plt.subplots()
# ax.set_xlim(-3e11, 3e11)
# ax.set_ylim(-3e11, 3e11)
# body1, = ax.plot([], [], 'ro', markersize=10)  # Red dot for body 1
# body2, = ax.plot([], [], 'bo', markersize=10)  # Blue dot for body 2
# trail1, = ax.plot([], [], 'r-', alpha=0.5)     # Trail for body 1
# trail2, = ax.plot([], [], 'b-', alpha=0.5)     # Trail for body 2
# def init():
#     body1.set_data([], [])
#     body2.set_data([], [])
#     trail1.set_data([], [])
#     trail2.set_data([], [])
#     return body1, body2, trail1, trail2

# # Add flexibility for frame step interval
# frame_step = 10  # Adjust as needed for different simulation speeds
# def update(frame): 
#     body1.set_data(positions1[frame, 0], positions1[frame, 1])
#     body2.set_data(positions2[frame, 0], positions2[frame, 1])
#     trail1.set_data(positions1[:frame, 0], positions1[:frame, 1])
#     trail2.set_data(positions2[:frame, 0], positions2[:frame, 1])
#     return body1, body2, trail1, trail2

# ani = animation.FuncAnimation(fig, update, frames=range(0, num_steps+1, frame_step),
#                               init_func=init, blit=True)

# plt.title("Binary Star System Simulation", fontsize=16, fontweight='bold', color='navy')
# plt.xlabel("x-position (m)", fontsize=14, color='darkgreen')
# plt.ylabel("y-position (m)", fontsize=14, color='darkgreen')

# plt.show()


In [25]:
positions2

array([[ 9.99666285e+10, -1.50000000e+09],
       [ 9.98998738e+10, -2.99958259e+09],
       [ 9.97997205e+10, -4.49832960e+09],
       ...,
       [ 7.47280693e+10, -7.56855061e+11],
       [ 7.33497109e+10, -7.58099258e+11],
       [ 7.19307797e+10, -7.59323138e+11]])

In [26]:
positions1

array([[-9.99749714e+10,  1.00000000e+09],
       [-9.99249054e+10,  1.99968694e+09],
       [-9.98497904e+10,  2.99874720e+09],
       ...,
       [-8.10460520e+10, -6.82108704e+11],
       [-8.00122832e+10, -6.81300557e+11],
       [-7.89480848e+10, -6.80507647e+11]])